precompile(SphericalHarmonicsCache, (Type{Float64}, Int, Type{FullRange}, ComplexHarmonics))
precompile(SphericalHarmonicsCache, (Type{Float64}, Int, Type{FullRange}, RealHarmonics))
precompile(SphericalHarmonicsCache, (Type{Float64}, Int, Type{ZeroTo}, ComplexHarmonics))
precompile(SphericalHarmonicsCache, (Type{Float64}, Int, Type{ZeroTo}, RealHarmonics))
_S = SphericalHarmonicsCache(Float64, 0, FullRange, ComplexHarmonics())
precompile(computePlmx!, (typeof(_S), Float64, Int))
precompile(computePlmx!, (typeof(_S.P), Float64, Int))
precompile(computePlmcostheta!, (typeof(_S), Float64, Int))
precompile(computePlmcostheta!, (typeof(_S.P), Float64, Int))
precompile(computeYlm!, (typeof(_S), Float64, Float64, Int))
